* further fix to whatever bug number it was with ties * some scons crap
git-svn-id: http://svn.code.sf.net/p/rosegarden/code/trunk@6392 cf6a83e7-f017-4305-b0b3-678bde24f230

diff --git a/rosegarden/scripts/cc_run b/rosegarden/scripts/cc_run
--- a/rosegarden/scripts/cc_run
+++ b/rosegarden/scripts/cc_run
@@ -1,3 +1,12 @@
 #!/bin/sh
+prefix=/opt/rosegarden-installs
 tag="$1"; shift
-PATH="/opt/rosegarden-installs/$tag/bin" KDEDIRS="/opt/rosegarden-installs/$tag" rosegarden "$@"
+if [ -z "$tag" ]; then
+    echo "Usage: $0 <tag>"
+    exit 2
+fi
+if [ ! -d "$prefix/$tag" ]; then
+    echo "No such tag as $tag (directory $prefix/$tag not found)"
+    exit 1
+fi
+PATH="$prefix/$tag/bin:$PATH" KDEDIRS="/opt/rosegarden-installs/$tag" "$prefix/$tag/bin/rosegarden" "$@"
