* Further to Emanuel's previous commit:   - "type sox" should print out some informative line other than just the     path, but "type -path sox" should print out only the path, so it should     have worked OK.  However I notice that the POSIX manpage for type lists     no options, so perhaps -path was nonportable.     I've never heard of "whereis", but the traditional Unix command     equivalent for the (usually shell built-in) "type -path" is called     "which", and I've inserted that instead.   - The reason for the grep polyphase is because sox can be built with any     combination of supported effects, and a sox without a resampler effect     (polyphase is the only one we could use) is as useless as no sox at all.     So I've reinstated this, but also added support for the more modern     "rabbit" effect (which is libsamplerate).
For what it's worth, I still haven't seen a thorough description of any
failure to use sox in this script that couldn't ultimately be tracked down
to a distro package dependency problem (i.e. the right bit of sox is not
installed), but perhaps I just haven't been paying enough attention.



git-svn-id: http://svn.code.sf.net/p/rosegarden/code/trunk/rosegarden@9602 cf6a83e7-f017-4305-b0b3-678bde24f230

diff --git a/src/helpers/rosegarden-audiofile-importer b/src/helpers/rosegarden-audiofile-importer
--- a/src/helpers/rosegarden-audiofile-importer
+++ b/src/helpers/rosegarden-audiofile-importer
@@ -51,21 +51,15 @@ echo "rosegarden-audiofile-importer: $@" 1>&2
 conftest() {
     # ssrc is our favourite resampler, but it only works for certain
     # samplerates, so we have to have at least one other just in case
-    if [ -x "`type -path sndfile-resample`" ]; then
+    if [ -x "`which sndfile-resample`" ]; then
 	return 0
     fi
-    # note by em-rumpf:
-    # `type -path sox` caused errors
-    # I replacaed with 'whereis' command and 'awk'
-    if [ -x "`whereis sox | awk '{print $2}'`" ] ; then
-        # note: I also removed the grep for "polyphase"
-        # the syntax seemed wrong too
-        # I don't know the reason for the grep - does anyone?
-        # 
-        ### && sox -h 2>&1 | grep -q polyphase; then
-	return 0
+    if [ -x "`which sox`" ]; then
+	if sox -h 2>&1 | egrep -q '(polyphase|rabbit)'; then
+	    return 0
+	fi
     fi
-    echo "Required: sox OR sndfile-resample"
+    echo "Required: sox with polyphase or rabbit resampler OR sndfile-resample"
     echo "rosegarden-audiofile-importer: ERROR: No resampler available, failing configuration test" 1>&2
     return 1
 }
@@ -211,7 +205,11 @@ resample() {
 	    sndfile-resample -to "$rate" -c 0 "$_source" "$_target" || return 4
 	else
 	    echo "Resampling using sox..." 1>&2
-	    sox "$_source" -r "$rate" "$_target" polyphase || return 4
+	    if sox -h | grep -q rabbit ; then
+	        sox "$_source" -r "$rate" "$_target" rabbit || return 4
+	    else
+		sox "$_source" -r "$rate" "$_target" polyphase || return 4
+	    fi
 	fi
     fi
     return 0
