updates from trunk
git-svn-id: http://svn.code.sf.net/p/rosegarden/code/branches/guitar_ktabedit@7838 cf6a83e7-f017-4305-b0b3-678bde24f230

diff --git a/src/helpers/rosegarden-lilypondview b/src/helpers/rosegarden-lilypondview
--- a/src/helpers/rosegarden-lilypondview
+++ b/src/helpers/rosegarden-lilypondview
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 tmpdir=/tmp/$$_lilypondview
 mkdir "$tmpdir" || exit 1
@@ -17,7 +17,7 @@ prog_terminal=""
 prog_ghostview=""
 
 if [ "$1" == "-v" ]; then
-    echo "rosegarden-lilypondview v1.2" 1>&2
+    echo "rosegarden-lilypondview v1.5" 1>&2
     shift
 fi
 
@@ -27,7 +27,7 @@ if [ "$?" != "0" ]; then
 else
     lilypond_version="`lilypond --version | grep LilyPond | head -1 | sed 's/^.* //'`"
     case "$lilypond_version" in
-	1.*|2.0.*)
+	1.*|2.[0-5].*)
 	    echo "rosegarden-lilypondview: Unsupported LilyPond version ($lilypond_version)" 1>&2;;
 	*)
 	    prog_lilypond=lilypond;;
@@ -41,7 +41,10 @@ for x in kghostview ggv ghostview; do
     fi
 done
 
+reqd=
+
 if [ -z "$prog_ghostview" ]; then
+    reqd="kghostview OR ggv OR ghostview, $reqd"
     echo "rosegarden-lilypondview: No PostScript viewer found" 1>&2
 fi
 
@@ -54,7 +57,14 @@ if [ -x "`type -path xterm`" ]; then
 fi
 
 if [ -z "$prog_terminal" ]; then
+    reqd="xterm, $reqd"
     echo "rosegarden-lilypondview: No terminal emulator found" 1>&2
+fi
+
+if [ "$1" == "--conftest" ]; then
+    if [ -n "$reqd" ]; then
+	echo "Required: "${reqd%%, }
+    fi
 fi
 
 [ -z "$prog_lilypond" ] && exit 1
@@ -123,15 +133,20 @@ cp "$input" "$tmpdir/" || exit 1
 	convert=""
 echo "LilyPond version is $lilypond_version, file version is $fileversion"
 	case "$lilypond_version" in
-	    2.2.*)
-		args="--no-pdf"
-		case "$fileversion" in
-		    1.*) convert=true;;
-		esac;;
 	    2.6.*)
-		args="--formats=ps"
+		args="--format=ps"
 		case "$fileversion" in
-		    1.*|2.[012].*) convert=true;;
+		    1.*|2.[0-5].*) convert=true;;
+		esac;;
+	    2.8.*)
+		args="--format=ps"
+		case "$fileversion" in
+		    1.*|2.[0-7].*) convert=true;;
+		esac;;
+	    2.10.*)
+		args="--format=ps"
+		case "$fileversion" in
+		    1.*|2.[0-9].*) convert=true;;
 		esac;;
 	esac
 
