* We can also make the Rosegarden dialog box show something useful if the user   has too old a version of LilyPond.
git-svn-id: http://svn.code.sf.net/p/rosegarden/code/trunk@7845 cf6a83e7-f017-4305-b0b3-678bde24f230

diff --git a/rosegarden/src/helpers/rosegarden-lilypondview b/rosegarden/src/helpers/rosegarden-lilypondview
--- a/rosegarden/src/helpers/rosegarden-lilypondview
+++ b/rosegarden/src/helpers/rosegarden-lilypondview
@@ -24,12 +24,13 @@ fi
 type -path lilypond
 if [ "$?" != "0" ]; then
     echo "rosegarden-lilypondview: LilyPond unavailable" 1>&2
-    echo "Required: lilypond"
+    echo "Required: LilyPond"
 else
     lilypond_version="`lilypond --version | grep LilyPond | head -1 | sed 's/^.* //'`"
     case "$lilypond_version" in
 	1.*|2.[0-5].*)
-	    echo "rosegarden-lilypondview: Unsupported LilyPond version ($lilypond_version)" 1>&2;;
+	    echo "rosegarden-lilypondview: Unsupported LilyPond version ($lilypond_version)" 1>&2
+	    echo "Required: LilyPond v2.6 or newer";;
 	*)
 	    prog_lilypond=lilypond;;
     esac
